# ~/.config/alacritty/alacritty.toml

[general]
live_config_reload = true
# working_directory = "None"
# ipc_socket = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[cursor]
style = "Block"
unfocused_hollow = true

[colors]
  [colors.primary]
  background = "0x1e1e2e"
  foreground = "0xcdd6f4"

  [colors.normal]
  black   = "0x1e1e2e"
  red     = "0xf38ba8"
  green   = "0xa6e3a1"
  yellow  = "0xf9e2af"
  blue    = "0x89b4fa"
  magenta = "0xf5c2e7"
  cyan    = "0x94e2d5"
  white   = "0xf5e0dc"

  [colors.bright]
  black   = "0x313244"
  red     = "0xf38ba8"
  green   = "0xa6e3a1"
  yellow  = "0xf9e2af"
  blue    = "0x89b4fa"
  magenta = "0xf5c2e7"
  cyan    = "0x94e2d5"
  white   = "0xf5e0dc"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
save_to_clipboard = true

